version: '3.8'
services:
  flask-proj:
    build: .
    ports:
      - "5000:8000"
    env_file: .env
    restart: always
    depends_on:
      - db
    
  db:
        image: postgres:14.3
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=test
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data: