version: '3.8'
services:
 
  db:
    image: postgres:14.3
    
    env_file: database.conf

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    
    ports:
      - 5432:5432  
    restart: always

  flask-proj:
    build: .
    ports:
      - "5000:5000"
    env_file: .env_docker
   
    restart: always
    depends_on:
      - db
       




volumes:
  postgres_data: 