version: '3.8'
services:
 
  db:
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: 12341
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # worker:
  #   image:  flask_proj:latest worker
  #   depends_on:
  #     - redis
  #   command: rq worker --name worker --url redis://redis:6379/0

  # dashboard:
  #   image: flask_proj
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis

  #   command: rq-dashboard --port 5555 --redis-url redis://redis:6379/0
  
  
  flask-proj:
    build: .
    ports:
      - "5000:5000"
    env_file: docker.env
   
    restart: always
    depends_on:
      - db
      




volumes:
  postgres_data: 
  # redis-data: