"""empty message

Revision ID: 69372df6ce25
Revises: cc083ec88fef
Create Date: 2022-06-11 12:38:55.139082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69372df6ce25'
down_revision = 'cc083ec88fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
