"""user tokens

Revision ID: 79c723e6408c
Revises: 82e1e278833b
Create Date: 2022-06-13 17:54:08.814854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c723e6408c'
down_revision = '82e1e278833b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contuct_us', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contuct_us', 'created')
    # ### end Alembic commands ###
