"""empty message

Revision ID: dda6a75cdf27
Revises: cbe0dcc14e4f
Create Date: 2022-05-12 16:27:03.197707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda6a75cdf27'
down_revision = 'cbe0dcc14e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
